%YAML 1.2
---

management.endpoints.web.exposure.include: mappings

server:
  error.path: /error
  error.whitelabel.enabled: false

spring:
  application.name: PartySheetShow
  data.mongodb.uri: "mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/${MONGO_DB}?appName=PartySheetShow"
  threads.virtual.enabled: true

open5e.client:
  pagination: 200
  default-gamesystem: "5e-2014"
  use-default-gamesystem: true